### PR TITLE
Neater way of doing the previous change

### PR DESCRIPTION
**Pull request by jhonny-oliveira**
Could you please bump the version tag as well?

### CODE REVIEW

**Comment by djjudas21** [comment]
That's a much neater way of doing it. What testing has it had?

**Comment by jhonny-oliveira** [comment]
​I only submitted after testing it on my environment... Why?

Best regards,
Jhonny Oliveira

**Comment by djjudas21** [comment]
I always ask what testing it's had, because sometimes people submit code that has never even been executed! I'm happy to accept both #9 and #10 and I'll tag a new release after. Thanks for your effort :+1:

**Comment by jhonny-oliveira** [comment]
That is also why I'm asking you to bump the version, because I would like
to have my environment versions (Tags) inline ​with yours.

Best regards,
Jhonny Oliveira

**Comment by djjudas21** [comment]
Cool. I've accepted the PRs, tagged release 0.4.1 and released it on Puppet Forge, too. Thanks!

**Comment by jhonny-oliveira** [comment]
Great! Thank you.

Best regards,
Jhonny Oliveira

**Pull request merged**
